version: '3.8'

services:
  socialbackenddb:
    container_name: social-backend-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: socialdb
      MYSQL_USER: socialuser
      MYSQL_PASSWORD: socialpassword
    ports:
      - "3307:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  apigatewayservice:
    container_name: api-gateway-app
    image: sithuramyo/api-gateway-app:latest
    ports:
      - "10000:10000"
      - "11000:11000"
    depends_on:
      - socialbackenddb
    environment:
      DB_HOST: socialbackenddb
      DB_PORT: 3306
      DB_NAME: socialdb
      DB_USER: socialuser
      DB_PASSWORD: socialpassword

  authenticationservice:
    container_name: social-backend-app
    image: sithuramyo/social-backend-app:latest
    ports:
      - "10001:10001"
      - "11001:11001"
    depends_on:
      - socialbackenddb
    environment:
      DB_HOST: socialbackenddb
      DB_PORT: 3306
      DB_NAME: socialdb
      DB_USER: socialuser
      DB_PASSWORD: socialpassword

volumes:
  db_data:
