version: '3.8'

services:
  socialbackenddb:
    container_name: social-backend-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: socialdb
      MYSQL_USER: socialuser
      MYSQL_PASSWORD: socialpassword
    ports:
      - "3307:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  apigatewayservice:
    container_name: api-gateway-app
    build:
      context: .
      dockerfile: ApiGatewayService/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - socialbackenddb
      - authenticationservice
      - socialmediaservice
    environment:
      DB_HOST: socialbackenddb
      DB_PORT: 3307
      DB_NAME: socialdb
      DB_USER: socialuser
      DB_PASSWORD: socialpassword

  authenticationservice:
    container_name: authentication-api-app
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - socialbackenddb
    environment:
      DB_HOST: social-backend-db
      DB_PORT: 3307
      DB_NAME: socialdb
      DB_USER: socialuser
      DB_PASSWORD: socialpassword
    
  socialmediaservice:
    container_name: socialmedia-api-app
    build:
      context: .
      dockerfile: SocialMediaService/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - socialbackenddb
    environment:
      DB_HOST: social-backend-db
      DB_PORT: 3307
      DB_NAME: socialdb
      DB_USER: socialuser
      DB_PASSWORD: socialpassword
        
volumes:
  db_data:
